### ISSUE TITLE
Spark not updating

### ISSUE THREAD

**Issue by MartinGonzalez** [shldk/raycast-macosicons#1]
Happy first issue!

I was able to replace Arc icon, but when doing it for Spark (email app) it does not replace it even the message says it was updated fine.

EDIT:
Finder also cannot be updated, perhaps is a permissions issue?

**Comment by shldk** [comment]
Hehe, yep, forgot to mention that in the readme. Starting from Big Sure I believe, Apple updated their security policy for system apps, and they can't be messed with without disabling SIP(which I strongly suggest you to keep enabled). 

And "system" apps also include apps installed thrugh App Store, I'm guessing that's where you installed it from, right?
I'm gonna research a little bit more, maybe someone smarter than me figured a workaround..  

Also 1 thing you might notice that after app updates itself, the icon is reset to default one, that's because when the app is updated, the whole bundle gets rewritten.

BTW to fix your particalar issue, you can just install it from official `.dmg` and then everything should work flawlessly. As added benefit you get app updates much earlier than App Store version. 

Hope this helps ;) And let me know if it worked or not!

**Comment by MartinGonzalez** [comment]
Perfect, makes a lot of sense about the system app. And Yes I installed Spark from the App Store.
Thanks for the clarification!

**Comment by Genxster1998** [comment]
can you provide option for SIP disabled system? Also it does same for apps installed from pkg installer. As almost 90 percent apps are from appstore.
